import { clamp, sin, tan, TAU } from "@r47onfire/game-math";
import { abs, round } from "lib0/math";
export const sgn = Math.sign;
export const ln = Math.log;
export const exp = Math.exp;
export const tanW = (x: number) => clamp(tan(x), -1, 1);
export const saw = (x: number) => 1 - (2 * x / TAU % 2 + 2) % 2;
export const tri = (x: number) => 1 - 4 * abs(round(x / TAU) - x / TAU);
export const noise3 = (x: number) => sin(x ** 3);
export const noise5 = (x: number) => sin(x ** 5);
