export const PI = Math.PI;
export const TAU = 2 * PI;
export const min = Math.min;
export const max = Math.max;
export const sqrt = Math.sqrt;
export const trunc = (x: number) => { var i = x | 0; return i - +(x < 0 && i != x); };
export const fract = (x: number) => x - trunc(x);
export const clamp = (x: number, y: number, z: number) => max(min(x, z), y);
export const sin = Math.sin;
export const cos = Math.cos;
export const sgn = Math.sign;
export const abs = Math.abs;
export const tan = Math.tan;
export const tanW = (x: number) => clamp(Math.tan(x), -1, 1);
export const saw = (x: number) => 1 - (2 * x / TAU % 2 + 2) % 2;
export const tri = (x: number) => 1 - 4 * abs(Math.round(x / TAU) - x / TAU);
export const noise3 = (x: number) => sin(x ** 3);
export const noise5 = (x: number) => sin(x ** 5);
export const lerp = (a: number, b: number, progress: number) => a * (1 - progress) + b * progress;
